resources:
- name: repo
  type: git
  source:
    uri: git@github.com:airtonix/concourse-resource-samba.git
    branch: master
    private_key: {{github-private-key}}
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:airtonix/concourse-resource-samba.git
    initial_version: "0.0.1"
    branch: version
    file: version
    private_key: {{github-private-key}}
- name: hub
  type: docker-image
  source:
    username: airtonix
    password: password
    repository: registry.thelma.lan/concourse-resource-samba
    insecure_registries: ["registry.thelma.lan"]

jobs:
- name: build
  public: true
  serial: true
  plan:
  - get: repo
    trigger: true
  - get: version
    params: {bump: patch}
  - put: hub
    params:
      build: repo
      tag: version/version
      tag_as_latest: true

- name: bump
  public: true
  serial: true
  plan:
  - get: hub
    passed: [build]
    trigger: true
  - get: version
    passed: [build]
  - put: version
    params:
      bump: patch
