resources:
- name: repo
  type: git
  source:
    uri: git@github.com:airtonix/concourse-resource-samba.git
    branch: master
    private_key: {{github-private-key}}
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:airtonix/concourse-resource-samba.git
    initial_version: "0.0.1"
    branch: version
    file: version
    private_key: {{github-private-key}}
- name: hub
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: airtonix/concourse-resource-samba

jobs:
- name: fetch
  public: true
  serial: true
  plan:
  - get: repo
    trigger: true
  - get: version
    params: {bump: patch}
- name: build
  public: true
  serial: true
  plan:
  - get: repo
    trigger: true
    passed: [fetch]
  - get: version
    passed: [fetch]
  - put: hub
    params:
      build: repo
      tag: version/version
      tag_as_latest: true
- name: bump
  public: true
  serial: true
  plan:
  - put: version
    passed: [build]
    params: {file: version/version}